export default [
  {
    id: 1,
    remarks:
      "Consider far understand. Morning start laugh though. You near majority identify design.\nSee space manage method. Time quickly above Republican if. Ever life method. Husband test hope offer degree.",
    start: "343 Rubio Island Suite 218\nEast Alexandriashire, NE 14329",
    end: "4735 Lisa Keys\nElizabethport, MS 86856",
    length_of_road: 11,
    zone: 8,
    district: "District-281",
    sub_category: "common city road",
    road_material: "Composite pavement",
    depth_of_road: 2,
    traffic_details: 2,
    heavy_vehicle_density: 46.01078208,
    light_four_wheeler_vehicle_density: 18.24859336,
    light_two_wheeler_vehicle_density: 51.07934613,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0,
    road_priority: 8.17,
  },
  {
    id: 2,
    remarks: "Draw nor white. Successful able should his over clearly thank.",
    start: "770 Walters Keys Suite 083\nWest Rachel, ND 72906",
    end: "370 Massey Canyon Apt. 730\nCarsontown, MA 79668",
    length_of_road: 99,
    zone: 9,
    district: "District-408",
    sub_category: "common city road",
    road_material: "gravel",
    depth_of_road: 8,
    traffic_details: 2,
    heavy_vehicle_density: 39.4468497,
    light_four_wheeler_vehicle_density: 94.64296079,
    light_two_wheeler_vehicle_density: 28.44224339,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.01,
    road_priority: 12.29,
  },
  {
    id: 3,
    remarks:
      "Able film rise us major. Measure themselves research pressure kind.\nSee different attention man author. Measure myself fill officer record.\nHard for prepare trouble.",
    start: "00059 Alexis Center Suite 065\nWest Shelly, MA 24709",
    end: "Unit 8284 Box 0425\nDPO AE 48970",
    length_of_road: 94,
    zone: 9,
    district: "District-130",
    sub_category: "common city road",
    road_material: "gravel",
    depth_of_road: 3,
    traffic_details: 1,
    heavy_vehicle_density: 12.36133576,
    light_four_wheeler_vehicle_density: 5.82842992,
    light_two_wheeler_vehicle_density: 81.56211375,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.02,
    road_priority: 6,
  },
  {
    id: 4,
    remarks:
      "Place enjoy never see film. Participant senior pick this happy.\nFriend movie like some together level artist.\nResult difficult team different. Why black one government.",
    start: "PSC 4481, Box 4121\nAPO AP 24179",
    end: "41508 Lozano Tunnel\nWest Deanna, IA 12483",
    length_of_road: 96,
    zone: 8,
    district: "District-11",
    sub_category: "Major District Road",
    road_material: "asphalt",
    depth_of_road: 9,
    traffic_details: 1,
    heavy_vehicle_density: 38.28001517,
    light_four_wheeler_vehicle_density: 10.35935189,
    light_two_wheeler_vehicle_density: 96.77333693,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.03,
    road_priority: 14.68,
  },
  {
    id: 5,
    remarks:
      "Send official college media. Fill evidence teacher. Model win station develop drug. Although within tree kind.\nNo building professional game. Teach method half minute look.",
    start: "27835 Miller Ports\nEast Gregory, NM 82070",
    end: "8702 Janice Ranch\nPort Justin, ND 40098",
    length_of_road: 55,
    zone: 2,
    district: "District-422",
    sub_category: "common city road",
    road_material: "concrete",
    depth_of_road: 7,
    traffic_details: 1,
    heavy_vehicle_density: 11.83654126,
    light_four_wheeler_vehicle_density: 35.30537776,
    light_two_wheeler_vehicle_density: 95.42838964,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.04,
    road_priority: 8.15,
  },
  {
    id: 6,
    remarks:
      "But center itself interview onto.\nStore either stage investment participant all. Charge deal church film job show serious. How yeah long administration choose leave high fact.",
    start: "900 Gregory Vista\nLake Zacharyberg, FL 24753",
    end: "0336 Bridget Cape\nLake Laura, IN 25698",
    length_of_road: 50,
    zone: 9,
    district: "District-143",
    sub_category: "State Highway",
    road_material: "asphalt",
    depth_of_road: 7,
    traffic_details: 1,
    heavy_vehicle_density: 13.22949513,
    light_four_wheeler_vehicle_density: 57.04145317,
    light_two_wheeler_vehicle_density: 12.96722852,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.05,
    road_priority: 12.31,
  },
  {
    id: 7,
    remarks:
      "Early see radio power worker.\nRemember assume none. Week go third something range natural growth contain. Staff carry commercial.\nLike reason modern nature. Some there glass prove.",
    start: "108 Emily Centers Apt. 760\nWest Jeffery, VA 74531",
    end: "6953 Jeffrey Point Suite 396\nSnowmouth, KS 76672",
    length_of_road: 29,
    zone: 1,
    district: "District-124",
    sub_category: "Major District Road",
    road_material: "Composite pavement",
    depth_of_road: 9,
    traffic_details: 1,
    heavy_vehicle_density: 25.15748385,
    light_four_wheeler_vehicle_density: 19.09831546,
    light_two_wheeler_vehicle_density: 78.30164631,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.06,
    road_priority: 16.48,
  },
  {
    id: 8,
    remarks:
      "Put court head right behavior physical. Interview protect light west president.\nDegree consumer push whole. Finally test sea travel theory war free. Read sit four statement despite fill.",
    start: "8683 Gabrielle Court Suite 686\nJesseborough, PA 89703",
    end: "USNS Wilson\nFPO AP 19945",
    length_of_road: 68,
    zone: 8,
    district: "District-491",
    sub_category: "Major District Road",
    road_material: "concrete",
    depth_of_road: 1,
    traffic_details: 2,
    heavy_vehicle_density: 12.6304156,
    light_four_wheeler_vehicle_density: 88.66258375,
    light_two_wheeler_vehicle_density: 91.7052584,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.07,
    road_priority: 4.36,
  },
  {
    id: 9,
    remarks:
      "Size child easy notice claim American interview.\nFilm I political customer story chair current. During goal fear throughout. Well hair international station arrive.",
    start: "81635 Tina Mill\nSouth Karen, NV 40039",
    end: "85233 David Rue\nPort Roberttown, OR 76004",
    length_of_road: 55,
    zone: 6,
    district: "District-360",
    sub_category: "common city road",
    road_material: "concrete",
    depth_of_road: 1,
    traffic_details: 2,
    heavy_vehicle_density: 41.59263196,
    light_four_wheeler_vehicle_density: 70.59734629,
    light_two_wheeler_vehicle_density: 76.53579551,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.08,
    road_priority: 10.06,
  },
  {
    id: 10,
    remarks:
      "Hundred six up watch inside rise poor. Particularly knowledge fact wife majority main. Should church author.\nPartner director difference at.",
    start: "8819 Amanda Knoll Apt. 591\nNew Gloriastad, LA 25932",
    end: "19466 Melissa Rue Suite 404\nJohnton, PA 78791",
    length_of_road: 14,
    zone: 8,
    district: "District-442",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 8,
    traffic_details: 2,
    heavy_vehicle_density: 19.96025698,
    light_four_wheeler_vehicle_density: 79.06479852,
    light_two_wheeler_vehicle_density: 97.40529499,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.09,
    road_priority: 16.89,
  },
  {
    id: 11,
    remarks:
      "Huge deal leader old star. New institution include.\nHard worry argue. Tonight society throw middle song music. Task order want effort.",
    start: "900 Bradley Lane Apt. 043\nSouth Stevenhaven, MT 77791",
    end: "3862 Kathy Shoal Apt. 664\nWilliamfort, MA 66961",
    length_of_road: 18,
    zone: 3,
    district: "District-177",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 8,
    traffic_details: 1,
    heavy_vehicle_density: 4.947192305,
    light_four_wheeler_vehicle_density: 88.21042341,
    light_two_wheeler_vehicle_density: 77.81043286,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.1,
    road_priority: 10.09,
  },
  {
    id: 12,
    remarks:
      "Financial small throughout open bag near. Turn safe with any left concern. Argue board past believe security role federal.\nFirm threat color trade position federal. Small if set none.",
    start: "010 Pruitt Walk\nWest Davidfort, VT 68798",
    end: "603 James Union\nNicholeville, MS 61193",
    length_of_road: 69,
    zone: 5,
    district: "District-329",
    sub_category: "common city road",
    road_material: "Composite pavement",
    depth_of_road: 7,
    traffic_details: 2,
    heavy_vehicle_density: 24.88443937,
    light_four_wheeler_vehicle_density: 25.53102146,
    light_two_wheeler_vehicle_density: 53.65245959,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.11,
    road_priority: 6.34,
  },
  {
    id: 13,
    remarks:
      "Month structure president store my explain run. Perform system find few most. Television already purpose their investment hair.\nConference form wide light. Think during draw.",
    start: "2893 Andrews Way Suite 921\nWest Richardville, DE 88284",
    end: "4394 Chang Prairie Suite 034\nBrianville, MS 61552",
    length_of_road: 69,
    zone: 2,
    district: "District-70",
    sub_category: "Major District Road",
    road_material: "concrete",
    depth_of_road: 4,
    traffic_details: 2,
    heavy_vehicle_density: 10.21076257,
    light_four_wheeler_vehicle_density: 49.29440988,
    light_two_wheeler_vehicle_density: 27.66064621,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.12,
    road_priority: 8.97,
  },
  {
    id: 14,
    remarks:
      "Standard at throughout become. Wish perhaps fund relate physical.\nRequire mean dream region. Discover stock choose he fact debate. Outside stay task matter.",
    start: "4213 Baker Neck\nAnthonyborough, KY 09548",
    end: "92980 Brooke Route Apt. 374\nWilliamberg, MD 33684",
    length_of_road: 68,
    zone: 6,
    district: "District-52",
    sub_category: "Major District Road",
    road_material: "asphalt",
    depth_of_road: 9,
    traffic_details: 1,
    heavy_vehicle_density: 37.66713533,
    light_four_wheeler_vehicle_density: 95.15002045,
    light_two_wheeler_vehicle_density: 37.1206885,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.13,
    road_priority: 12.72,
  },
  {
    id: 15,
    remarks:
      "Major population say protect head. Then five series eat effort. Care treat issue home.\nMedia this page natural enjoy. Modern certainly experience artist.",
    start: "8427 Robert Ports\nSouth Rickystad, NE 89682",
    end: "52625 Cory Way Suite 546\nDavishaven, MO 81465",
    length_of_road: 76,
    zone: 6,
    district: "District-291",
    sub_category: "State Highway",
    road_material: "concrete",
    depth_of_road: 3,
    traffic_details: 1,
    heavy_vehicle_density: 29.52498056,
    light_four_wheeler_vehicle_density: 84.90843469,
    light_two_wheeler_vehicle_density: 81.29610517,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.14,
    road_priority: 6.32,
  },
  {
    id: 16,
    remarks:
      "Maintain both unit health standard. View benefit job drive recognize enough.\nApply cell issue decade or medical. Response happen probably specific.\nSuch mission often theory teacher.",
    start: "1471 Julie Highway Apt. 147\nJensenchester, SC 46807",
    end: "50509 Bethany Valley\nJosephborough, PA 26831",
    length_of_road: 86,
    zone: 2,
    district: "District-283",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 2,
    traffic_details: 1,
    heavy_vehicle_density: 12.78755053,
    light_four_wheeler_vehicle_density: 35.76907792,
    light_two_wheeler_vehicle_density: 45.91466352,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.15,
    road_priority: 8.55,
  },
  {
    id: 17,
    remarks:
      "West east official reality again true. Learn indeed difficult laugh option participant. Stay service to central.",
    start: "787 Kayla Lake Suite 586\nTarashire, NV 40546",
    end: "83513 Gregory Hollow\nJohnsonmouth, WY 66545",
    length_of_road: 10,
    zone: 9,
    district: "District-128",
    sub_category: "National Highway",
    road_material: "concrete",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 37.70200574,
    light_four_wheeler_vehicle_density: 87.79152974,
    light_two_wheeler_vehicle_density: 56.30239939,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.16,
    road_priority: 8.35,
  },
  {
    id: 18,
    remarks:
      "Young sea score. Friend price red data letter among property. Throughout participant character detail. Single almost spring pay language for down stay.\nSimple whole serious contain do.",
    start: "4124 Rhonda Track Suite 831\nLake Kristy, WA 89385",
    end: "504 Ashley Oval\nEast Judith, SC 57493",
    length_of_road: 21,
    zone: 8,
    district: "District-55",
    sub_category: "Major District Road",
    road_material: "concrete",
    depth_of_road: 1,
    traffic_details: 2,
    heavy_vehicle_density: 6.681528381,
    light_four_wheeler_vehicle_density: 95.20224994,
    light_two_wheeler_vehicle_density: 68.24142343,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.17,
    road_priority: 10.64,
  },
  {
    id: 19,
    remarks:
      "At recognize around during moment case bit. Five home unit tonight.\nNation member off despite cold fast past. Ten pressure son perhaps feel back great actually. A term try list base.",
    start: "3772 Alison Burgs Apt. 062\nWest Beth, GA 45313",
    end: "681 Adams Route\nSaraburgh, HI 00682",
    length_of_road: 29,
    zone: 4,
    district: "District-249",
    sub_category: "State Highway",
    road_material: "Composite pavement",
    depth_of_road: 4,
    traffic_details: 2,
    heavy_vehicle_density: 12.72783367,
    light_four_wheeler_vehicle_density: 52.28154883,
    light_two_wheeler_vehicle_density: 91.80237109,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.18,
    road_priority: 8.21,
  },
  {
    id: 20,
    remarks:
      "Billion school know air dinner pretty. Position serve might plant easy it ago likely. Water the international community since senior million sort.",
    start: "Unit 4985 Box 6113\nDPO AE 69190",
    end: "60839 Deanna Circles Apt. 830\nThomastown, SD 27580",
    length_of_road: 48,
    zone: 9,
    district: "District-219",
    sub_category: "Major District Road",
    road_material: "asphalt",
    depth_of_road: 1,
    traffic_details: 1,
    heavy_vehicle_density: 24.12013803,
    light_four_wheeler_vehicle_density: 37.32162019,
    light_two_wheeler_vehicle_density: 18.54916285,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.19,
    road_priority: 4.94,
  },
  {
    id: 21,
    remarks:
      "Happen admit safe investment size foot. Picture as agency top appear region live. Financial town remain television evening exactly understand.",
    start: "26685 Amy Grove Suite 212\nEast Gregory, MA 83971",
    end: "214 Jeffrey Expressway\nWest Jeromefurt, FL 70073",
    length_of_road: 81,
    zone: 9,
    district: "District-403",
    sub_category: "common city road",
    road_material: "gravel",
    depth_of_road: 9,
    traffic_details: 2,
    heavy_vehicle_density: 2.202598331,
    light_four_wheeler_vehicle_density: 43.58025361,
    light_two_wheeler_vehicle_density: 56.99787512,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.2,
    road_priority: 10.75,
  },
  {
    id: 22,
    remarks:
      "Stop interview spend head argue raise house yes. Bring soldier task himself class industry.\nHealth field choice.",
    start: "496 Gallegos Fields Suite 919\nSouth Kenneth, NY 35026",
    end: "133 Thompson Mountain\nAlexanderfurt, IN 95078",
    length_of_road: 30,
    zone: 1,
    district: "District-28",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 7,
    traffic_details: 1,
    heavy_vehicle_density: 30.677734,
    light_four_wheeler_vehicle_density: 51.86604034,
    light_two_wheeler_vehicle_density: 39.31402759,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.21,
    road_priority: 10.76,
  },
  {
    id: 23,
    remarks:
      "End base Democrat measure than. Option series respond issue.\nWind significant its stop discussion sea only book. Begin me quickly month. Agency song source surface.",
    start: "10356 Thompson Brook\nEast John, IN 87762",
    end: "9037 Omar Crest Apt. 461\nPrestontown, DC 35032",
    length_of_road: 87,
    zone: 2,
    district: "District-22",
    sub_category: "common city road",
    road_material: "asphalt",
    depth_of_road: 5,
    traffic_details: 2,
    heavy_vehicle_density: 45.24211767,
    light_four_wheeler_vehicle_density: 75.17141714,
    light_two_wheeler_vehicle_density: 15.90711394,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.22,
    road_priority: 6.58,
  },
  {
    id: 24,
    remarks:
      "Yet seat world represent so our deal bed. Million firm majority next.\nCar camera respond baby. Expert role offer out. Station day who.",
    start: "12802 Shelby Cape\nStewarttown, OH 60360",
    end: "2633 Pena Valley Suite 863\nElliottmouth, WA 28241",
    length_of_road: 11,
    zone: 9,
    district: "District-193",
    sub_category: "common city road",
    road_material: "gravel",
    depth_of_road: 7,
    traffic_details: 1,
    heavy_vehicle_density: 41.48834386,
    light_four_wheeler_vehicle_density: 91.31135671,
    light_two_wheeler_vehicle_density: 74.48397594,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.23,
    road_priority: 14.12,
  },
  {
    id: 25,
    remarks:
      "Term blue skill staff. Firm college find.\nBag newspaper happy blood identify compare for participant. Last wall kid north measure current. Huge myself anything rise play age.",
    start: "277 Phillip Rue\nSouth Michaelberg, TX 89105",
    end: "6223 Candice Mountain Suite 164\nIanshire, ME 56209",
    length_of_road: 63,
    zone: 9,
    district: "District-68",
    sub_category: "State Highway",
    road_material: "asphalt",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 44.28484938,
    light_four_wheeler_vehicle_density: 91.91644641,
    light_two_wheeler_vehicle_density: 69.49187796,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.24,
    road_priority: 8.36,
  },
  {
    id: 26,
    remarks:
      "Represent explain suddenly decision. Pm cultural hope shake drug name. Toward after suffer.",
    start: "029 Jones Mission\nKatherineland, MA 16043",
    end: "52069 Obrien Route\nPort Julie, IL 08544",
    length_of_road: 19,
    zone: 3,
    district: "District-310",
    sub_category: "Major District Road",
    road_material: "concrete",
    depth_of_road: 2,
    traffic_details: 1,
    heavy_vehicle_density: 6.216913137,
    light_four_wheeler_vehicle_density: 62.16744881,
    light_two_wheeler_vehicle_density: 29.2791927,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.25,
    road_priority: 14.72,
  },
  {
    id: 27,
    remarks:
      "Grow outside dinner within indeed me live result. Against impact plan method specific guy. Social wide southern return.\nOnto suffer responsibility production thing dinner need begin.",
    start: "0517 Stone Shoal Apt. 804\nWest Jenniferborough, WY 56688",
    end: "4906 Rodriguez Trail\nTiffanyburgh, WY 82216",
    length_of_road: 3,
    zone: 2,
    district: "District-82",
    sub_category: "State Highway",
    road_material: "concrete",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 4.445306637,
    light_four_wheeler_vehicle_density: 79.34992164,
    light_two_wheeler_vehicle_density: 38.07127403,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.26,
    road_priority: 14.29,
  },
  {
    id: 28,
    remarks:
      "Owner stand Mr stuff just north. Training long open.\nHappy throughout daughter player. Certain idea hear interesting. Bad TV beat involve music purpose anyone.",
    start: "521 Williams Manor Apt. 735\nMullinsborough, NM 10860",
    end: "286 Margaret Path\nAmberchester, TN 74213",
    length_of_road: 16,
    zone: 1,
    district: "District-128",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 13.93616313,
    light_four_wheeler_vehicle_density: 43.15251049,
    light_two_wheeler_vehicle_density: 11.95808537,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.27,
    road_priority: 8.99,
  },
  {
    id: 29,
    remarks:
      "Which look movement nothing sort mission response. Tough size police door spend case watch.",
    start: "8442 Sherman Brooks Apt. 589\nJohnsonport, AZ 81873",
    end: "USNS Carpenter\nFPO AA 10038",
    length_of_road: 55,
    zone: 1,
    district: "District-484",
    sub_category: "National Highway",
    road_material: "concrete",
    depth_of_road: 7,
    traffic_details: 1,
    heavy_vehicle_density: 13.29454372,
    light_four_wheeler_vehicle_density: 92.43668705,
    light_two_wheeler_vehicle_density: 77.24210451,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.28,
    road_priority: 8.72,
  },
  {
    id: 30,
    remarks:
      "Believe action instead very though position. Bed man high draw choose. Doctor benefit job majority glass book wear there.",
    start: "38305 Price Divide Suite 553\nJonstad, NV 21790",
    end: "11701 Smith Crest Suite 269\nEast Brookebury, NJ 57598",
    length_of_road: 59,
    zone: 9,
    district: "District-58",
    sub_category: "National Highway",
    road_material: "gravel",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 37.32645857,
    light_four_wheeler_vehicle_density: 76.22594227,
    light_two_wheeler_vehicle_density: 39.17794883,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.29,
    road_priority: 14.62,
  },
  {
    id: 31,
    remarks:
      "Enter need right game deep usually work. Wonder something they middle four reduce character. Worry again total pretty long. Hour sure begin.",
    start: "91812 Myers Courts Apt. 509\nCarolynland, NM 13995",
    end: "648 Holmes Union\nTranmouth, MA 77574",
    length_of_road: 86,
    zone: 8,
    district: "District-269",
    sub_category: "State Highway",
    road_material: "asphalt",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 28.07683347,
    light_four_wheeler_vehicle_density: 2.630014596,
    light_two_wheeler_vehicle_density: 6.172230053,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.3,
    road_priority: 16.75,
  },
  {
    id: 32,
    remarks:
      "Require allow save expert. Election or feel some include realize. Someone leg difference couple.\nModern moment everything course leader meet behind. Husband theory manage. Let former protect write.",
    start: "71072 Julie Locks\nJosephborough, KY 63721",
    end: "797 Shane Way Suite 657\nPort Michelleview, VT 20491",
    length_of_road: 6,
    zone: 7,
    district: "District-161",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 5,
    traffic_details: 2,
    heavy_vehicle_density: 28.72041449,
    light_four_wheeler_vehicle_density: 69.57397513,
    light_two_wheeler_vehicle_density: 1.062353583,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.31,
    road_priority: 14.25,
  },
  {
    id: 33,
    remarks:
      "Stock where interesting use southern floor safe television. Industry instead training remain I mind. Lot network officer.\nPlay claim stay society security. Hard public relate organization.",
    start: "2497 Janice Turnpike Suite 854\nAlvaradofurt, DC 33271",
    end: "45847 Miller Cliffs Apt. 330\nNew Randall, LA 91243",
    length_of_road: 91,
    zone: 9,
    district: "District-39",
    sub_category: "National Highway",
    road_material: "concrete",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 0.9514076285,
    light_four_wheeler_vehicle_density: 57.5461911,
    light_two_wheeler_vehicle_density: 81.93094998,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.32,
    road_priority: 12.61,
  },
  {
    id: 34,
    remarks:
      "Note citizen from difference. Medical beat realize half stand strategy.\nBlood my whatever always. Film city never impact try nature century.",
    start: "984 Hardin Ville\nJoefurt, NC 38593",
    end: "291 Jones Landing\nAnitaport, KS 61146",
    length_of_road: 11,
    zone: 1,
    district: "District-401",
    sub_category: "State Highway",
    road_material: "concrete",
    depth_of_road: 9,
    traffic_details: 1,
    heavy_vehicle_density: 37.30946184,
    light_four_wheeler_vehicle_density: 36.62678474,
    light_two_wheeler_vehicle_density: 36.54317538,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.33,
    road_priority: 12.18,
  },
  {
    id: 35,
    remarks:
      "Term hundred walk operation later job direction. Five a always beautiful friend production. Similar especially force soon data knowledge.",
    start: "34657 Nathan Drive\nHallstad, HI 62688",
    end: "029 Elizabeth Lodge\nMillermouth, SD 21316",
    length_of_road: 63,
    zone: 2,
    district: "District-345",
    sub_category: "common city road",
    road_material: "asphalt",
    depth_of_road: 8,
    traffic_details: 2,
    heavy_vehicle_density: 46.40014158,
    light_four_wheeler_vehicle_density: 88.53574276,
    light_two_wheeler_vehicle_density: 26.69553361,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.34,
    road_priority: 14.65,
  },
  {
    id: 36,
    remarks:
      "Arrive base power arm maintain technology determine argue. Dog necessary nice imagine paper assume.\nShould building eat whose can picture six. Much fight almost network building high.",
    start: "605 Braun Causeway Suite 209\nWest Madison, MS 78388",
    end: "6345 Emily Ramp\nCraigville, AR 97744",
    length_of_road: 98,
    zone: 2,
    district: "District-356",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 4,
    traffic_details: 1,
    heavy_vehicle_density: 45.28396844,
    light_four_wheeler_vehicle_density: 71.62912199,
    light_two_wheeler_vehicle_density: 49.73290411,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.35,
    road_priority: 12.88,
  },
  {
    id: 37,
    remarks:
      "Site interest if letter like spring risk participant. What suggest kind against popular always focus cup.",
    start: "6020 Victoria Bypass Apt. 472\nPort Sandramouth, WA 06291",
    end: "08832 Carrie Harbors\nMatthewfurt, NJ 36869",
    length_of_road: 75,
    zone: 1,
    district: "District-291",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 7,
    traffic_details: 1,
    heavy_vehicle_density: 1.92989242,
    light_four_wheeler_vehicle_density: 85.47789877,
    light_two_wheeler_vehicle_density: 0.1222586858,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.36,
    road_priority: 12.97,
  },
  {
    id: 38,
    remarks:
      "Someone argue rise score full my. Ok from central apply again ever. Kind woman range computer already difference increase. System nature loss accept ever structure.",
    start: "080 Steele Valleys\nBennettfurt, MD 42249",
    end: "56360 Wendy Parks Apt. 488\nWest Maurice, WY 10928",
    length_of_road: 47,
    zone: 6,
    district: "District-92",
    sub_category: "National Highway",
    road_material: "Composite pavement",
    depth_of_road: 4,
    traffic_details: 2,
    heavy_vehicle_density: 1.712752846,
    light_four_wheeler_vehicle_density: 18.15303581,
    light_two_wheeler_vehicle_density: 0.8144612887,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.37,
    road_priority: 8.39,
  },
  {
    id: 39,
    remarks:
      "Identify since security sign believe will. Voice various station herself.\nSchool economic until crime magazine believe. I nothing can wait political owner treat. Off large speak how.",
    start: "9168 Flores Loop\nJameston, IN 90495",
    end: "861 Patricia Prairie\nSouth Wendy, NM 68529",
    length_of_road: 37,
    zone: 8,
    district: "District-392",
    sub_category: "common city road",
    road_material: "asphalt",
    depth_of_road: 7,
    traffic_details: 2,
    heavy_vehicle_density: 31.1433392,
    light_four_wheeler_vehicle_density: 72.97710469,
    light_two_wheeler_vehicle_density: 27.11725125,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.38,
    road_priority: 10.29,
  },
  {
    id: 40,
    remarks:
      "Establish cold glass enough onto dog. Necessary mind Mrs building.\nSouth last understand hair establish. Them discover present act forget value memory.",
    start: "0571 Roberts Club Apt. 728\nJohnsonland, CA 85962",
    end: "1800 Nicole Loop\nEast Seanhaven, CT 39491",
    length_of_road: 66,
    zone: 6,
    district: "District-164",
    sub_category: "National Highway",
    road_material: "gravel",
    depth_of_road: 8,
    traffic_details: 1,
    heavy_vehicle_density: 27.85595365,
    light_four_wheeler_vehicle_density: 12.83388506,
    light_two_wheeler_vehicle_density: 61.42695944,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.39,
    road_priority: 6.61,
  },
  {
    id: 41,
    remarks:
      "Us table today. Class economic partner career easy training. Peace truth land.\nAble senior somebody return. Project coach media second have artist. Stage place can century final case.",
    start: "08177 Christopher Fall\nPort Jennifer, NJ 88449",
    end: "9660 Davis Islands\nMelissahaven, NC 75585",
    length_of_road: 74,
    zone: 1,
    district: "District-393",
    sub_category: "National Highway",
    road_material: "Composite pavement",
    depth_of_road: 6,
    traffic_details: 1,
    heavy_vehicle_density: 13.13814547,
    light_four_wheeler_vehicle_density: 99.90462286,
    light_two_wheeler_vehicle_density: 22.01705881,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.4,
    road_priority: 12.74,
  },
  {
    id: 42,
    remarks:
      "Television particular production me nice source participant. Such box upon floor force national spring.\nCentury suddenly southern simple friend book course one. Summer win table method find.",
    start: "52069 Jackson Light Suite 748\nPort Patrickberg, NC 69350",
    end: "26457 Stephanie Trail Apt. 993\nWest Gregoryland, TN 56359",
    length_of_road: 49,
    zone: 5,
    district: "District-459",
    sub_category: "National Highway",
    road_material: "Composite pavement",
    depth_of_road: 5,
    traffic_details: 2,
    heavy_vehicle_density: 32.00908058,
    light_four_wheeler_vehicle_density: 66.28469154,
    light_two_wheeler_vehicle_density: 77.75333111,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.41,
    road_priority: 8.65,
  },
  {
    id: 43,
    remarks:
      "Ask idea set space billion sell. Open get born newspaper week. Democratic across phone election against.\nNetwork interview gas stay job. What season modern expert over.",
    start: "7689 Caitlin Cove\nPort Christopher, IA 67799",
    end: "37706 Watts Gateway\nSouth Cameronside, IN 44941",
    length_of_road: 11,
    zone: 3,
    district: "District-75",
    sub_category: "common city road",
    road_material: "concrete",
    depth_of_road: 5,
    traffic_details: 2,
    heavy_vehicle_density: 45.0909191,
    light_four_wheeler_vehicle_density: 38.44112813,
    light_two_wheeler_vehicle_density: 32.61368863,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.42,
    road_priority: 8.52,
  },
  {
    id: 44,
    remarks:
      "Economic manage practice send plan win stop. West debate far herself indeed rock clear. Interview body program choice daughter we.",
    start: "0020 Munoz Glen Suite 043\nSheenatown, MS 90370",
    end: "885 Christine Valley Suite 996\nSouth Kenneth, MN 76992",
    length_of_road: 8,
    zone: 4,
    district: "District-495",
    sub_category: "Major District Road",
    road_material: "asphalt",
    depth_of_road: 3,
    traffic_details: 2,
    heavy_vehicle_density: 2.366910107,
    light_four_wheeler_vehicle_density: 86.96282914,
    light_two_wheeler_vehicle_density: 79.87608269,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.43,
    road_priority: 12.15,
  },
  {
    id: 45,
    remarks:
      "Skin loss individual animal agreement. Traditional city data real nature assume people. And end to next such inside which.",
    start: "09409 Meyers Way Suite 145\nSamanthaville, OK 49176",
    end: "14384 Cassandra Ramp Apt. 849\nBonniemouth, PA 94824",
    length_of_road: 94,
    zone: 2,
    district: "District-265",
    sub_category: "common city road",
    road_material: "gravel",
    depth_of_road: 5,
    traffic_details: 1,
    heavy_vehicle_density: 23.84320399,
    light_four_wheeler_vehicle_density: 50.25245506,
    light_two_wheeler_vehicle_density: 39.29401564,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.44,
    road_priority: 10.25,
  },
  {
    id: 46,
    remarks:
      "Area tend church out find choose rich. Chair I catch toward above win no.\nEnjoy other young. Clear investment well.",
    start: "386 Crawford Square Suite 206\nWest Dorisland, MN 19094",
    end: "3605 Cynthia Ramp Apt. 191\nDavidmouth, MA 00975",
    length_of_road: 1,
    zone: 4,
    district: "District-286",
    sub_category: "Major District Road",
    road_material: "gravel",
    depth_of_road: 4,
    traffic_details: 1,
    heavy_vehicle_density: 40.3486202,
    light_four_wheeler_vehicle_density: 20.23188116,
    light_two_wheeler_vehicle_density: 6.370504386,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.45,
    road_priority: 8.45,
  },
  {
    id: 47,
    remarks:
      "Half account song dinner investment. Right national soon if low few step.\nApproach suggest girl one front. Show hair yeah with. Toward medical possible answer third office.",
    start: "Unit 2710 Box 3563\nDPO AE 38753",
    end: "0476 John Summit\nBarryland, NM 91749",
    length_of_road: 5,
    zone: 8,
    district: "District-471",
    sub_category: "common city road",
    road_material: "Composite pavement",
    depth_of_road: 3,
    traffic_details: 1,
    heavy_vehicle_density: 25.46646981,
    light_four_wheeler_vehicle_density: 51.76762466,
    light_two_wheeler_vehicle_density: 93.4574734,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.46,
    road_priority: 12.12,
  },
  {
    id: 48,
    remarks:
      "Yard economic anyone including because weight onto. Prevent face suddenly they how low sometimes. Positive return put determine case almost side.",
    start: "91806 Barbara Freeway Suite 346\nLake Jessicaville, NE 31332",
    end: "503 Carlson Plaza Suite 968\nBrownview, AL 86811",
    length_of_road: 59,
    zone: 7,
    district: "District-35",
    sub_category: "Major District Road",
    road_material: "concrete",
    depth_of_road: 7,
    traffic_details: 2,
    heavy_vehicle_density: 38.9311112,
    light_four_wheeler_vehicle_density: 46.75886567,
    light_two_wheeler_vehicle_density: 33.44083721,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.47,
    road_priority: 6.84,
  },
  {
    id: 49,
    remarks:
      "Live black task out. Learn black gas truth feel a time me. Leave edge quality candidate role protect contain write.",
    start: "87582 Williams Station\nEast Paulhaven, NE 71769",
    end: "59797 Lowe Ferry\nBishopville, NC 20015",
    length_of_road: 25,
    zone: 2,
    district: "District-279",
    sub_category: "National Highway",
    road_material: "concrete",
    depth_of_road: 6,
    traffic_details: 2,
    heavy_vehicle_density: 13.0071221,
    light_four_wheeler_vehicle_density: 27.65220768,
    light_two_wheeler_vehicle_density: 38.14209193,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.48,
    road_priority: 10.6,
  },
  {
    id: 50,
    remarks:
      "Language difference agency. Especially available eight response.\nAlmost she for bed degree image together.\nTotal follow up piece develop keep. Put peace since read. Later all feeling.",
    start: "52102 Joseph Prairie\nWest Hannahton, KY 53690",
    end: "902 Christian Views Suite 225\nNew Johnfort, VT 17127",
    length_of_road: 71,
    zone: 1,
    district: "District-113",
    sub_category: "National Highway",
    road_material: "asphalt",
    depth_of_road: 9,
    traffic_details: 1,
    heavy_vehicle_density: 8.934117598,
    light_four_wheeler_vehicle_density: 3.509724976,
    light_two_wheeler_vehicle_density: 39.79947058,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.49,
    road_priority: 12.7,
  },
  {
    id: 51,
    remarks:
      "Hit type time notice alone. Four popular economy nearly. Health her edge you week former.",
    start: "94064 Joann Street\nNew Jeremy, SC 87222",
    end: "137 Hines Locks Apt. 309\nKingmouth, AR 20727",
    length_of_road: 57,
    zone: 2,
    district: "District-159",
    sub_category: "Major District Road",
    road_material: "asphalt",
    depth_of_road: 2,
    traffic_details: 2,
    heavy_vehicle_density: 19.76343711,
    light_four_wheeler_vehicle_density: 14.30382483,
    light_two_wheeler_vehicle_density: 43.20998996,
    connecting_features: 1,
    places: 1,
    number_of_complaints: 0.5,
    road_priority: 16.99,
  },
];